openapi: 3.0.3
info:
  description: Test API description.
  title: Test API
  version: 1.2.3
paths:
  /articles:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Article'
                type: array
          description: OK
components:
  schemas:
    Article:
      properties:
        id:
          type: string
        slug:
          type: string
        title:
          type: string
      type: object
